Upgrade in progress
Now to get a Solr instance up and running aside from the test runner

// identify overlapping schema
// remediate overlapping schema

// need mechanism to correct ...

Cleaning up more cruft left behind the hack and slash upgrade

Cleanup while running index...

Correct bad refactor. Try not to break Solr running tests.

jakarta.xml.bind.JAXBException: namespacePrefixMapper is null
        at org.docx4j.jaxb.NamespacePrefixMapperUtils.setProperty(NamespacePrefixMapperUtils.java:150) ~[docx4j-core-11.4.8.jar:na]
        at org.docx4j.openpackaging.contenttype.ContentTypeManager.marshal(ContentTypeManager.java:951) ~[docx4j-core-11.4.8.jar:na]
        at org.docx4j.openpackaging.io3.stores.ZipPartStore.saveContentTypes(ZipPartStore.java:313) ~[docx4j-core-11.4.8.jar:na]
        at org.docx4j.openpackaging.io3.Save.save(Save.java:177) ~[docx4j-core-11.4.8.jar:na]
        at org.docx4j.openpackaging.packages.OpcPackage.save(OpcPackage.java:799) ~[docx4j-core-11.4.8.jar:na]
        at org.docx4j.openpackaging.packages.OpcPackage.save(OpcPackage.java:729) ~[docx4j-core-11.4.8.jar:na]
        at org.docx4j.openpackaging.packages.OpcPackage.save(OpcPackage.java:717) ~[docx4j-core-11.4.8.jar:na]
        at edu.tamu.scholars.middleware.export.service.DocxExporter.lambda$streamIndividual$1(DocxExporter.java:150) ~[classes/:na]
        at org.springframework.web.servlet.mvc.method.annotation.StreamingResponseBodyReturnValueHandler$StreamingResponseBodyTask.call(StreamingResponseBodyReturnValueHandler.java:110) ~[spring-webmvc-6.0.6.jar:6.0.6]
        at org.springframework.web.servlet.mvc.method.annotation.StreamingResponseBodyReturnValueHandler$StreamingResponseBodyTask.call(StreamingResponseBodyReturnValueHandler.java:97) ~[spring-webmvc-6.0.6.jar:6.0.6]
        at org.springframework.web.context.request.async.WebAsyncManager.lambda$startCallableProcessing$4(WebAsyncManager.java:336) ~[spring-web-6.0.6.jar:6.0.6]
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) ~[na:na]
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[na:na]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[na:na]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[na:na]
        at java.base/java.lang.Thread.run(Thread.java:833) ~[na:na]

org.docx4j.openpackaging.exceptions.Docx4JException: Error marshalling Content_Types
        at org.docx4j.openpackaging.io3.stores.ZipPartStore.saveContentTypes(ZipPartStore.java:317)
        at org.docx4j.openpackaging.io3.Save.save(Save.java:177)
        at org.docx4j.openpackaging.packages.OpcPackage.save(OpcPackage.java:799)
        at org.docx4j.openpackaging.packages.OpcPackage.save(OpcPackage.java:729)
        at org.docx4j.openpackaging.packages.OpcPackage.save(OpcPackage.java:717)
        at edu.tamu.scholars.middleware.export.service.DocxExporter.lambda$streamIndividual$1(DocxExporter.java:150)
        at org.springframework.web.servlet.mvc.method.annotation.StreamingResponseBodyReturnValueHandler$StreamingResponseBodyTask.call(StreamingResponseBodyReturnValueHandler.java:110)
        at org.springframework.web.servlet.mvc.method.annotation.StreamingResponseBodyReturnValueHandler$StreamingResponseBodyTask.call(StreamingResponseBodyReturnValueHandler.java:97)
        at org.springframework.web.context.request.async.WebAsyncManager.lambda$startCallableProcessing$4(WebAsyncManager.java:336)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base/java.lang.Thread.run(Thread.java:833)