Upgrades (#264)
* Bump docx4j-ImportXHTML from 8.2.1 to 11.4.8

Bumps [docx4j-ImportXHTML](https://github.com/plutext/docx4j-ImportXHTML) from 8.2.1 to 11.4.8.
- [Release notes](https://github.com/plutext/docx4j-ImportXHTML/releases)
- [Changelog](https://github.com/plutext/docx4j-ImportXHTML/blob/VERSION_11_4_8/CHANGELOG.md)
- [Commits](https://github.com/plutext/docx4j-ImportXHTML/compare/docx4j-ImportXHTML-8.2.1...docx4j-ImportXHTML-parent-11.4.8)

---
updated-dependencies:
- dependency-name: org.docx4j:docx4j-ImportXHTML
  dependency-type: direct:production
  update-type: version-update:semver-major
...

Signed-off-by: dependabot[bot] <support@github.com>

* Bump asciidoctor-maven-plugin from 1.6.0 to 2.2.2

Bumps [asciidoctor-maven-plugin](https://github.com/asciidoctor/asciidoctor-maven-plugin) from 1.6.0 to 2.2.2.
- [Release notes](https://github.com/asciidoctor/asciidoctor-maven-plugin/releases)
- [Changelog](https://github.com/asciidoctor/asciidoctor-maven-plugin/blob/main/CHANGELOG.adoc)
- [Commits](https://github.com/asciidoctor/asciidoctor-maven-plugin/compare/asciidoctor-maven-plugin-1.6.0...asciidoctor-maven-plugin-2.2.2)

---
updated-dependencies:
- dependency-name: org.asciidoctor:asciidoctor-maven-plugin
  dependency-type: direct:production
  update-type: version-update:semver-major
...

Signed-off-by: dependabot[bot] <support@github.com>

* Bump spring-boot-starter-parent from 2.6.14 to 3.0.3

Bumps [spring-boot-starter-parent](https://github.com/spring-projects/spring-boot) from 2.6.14 to 3.0.3.
- [Release notes](https://github.com/spring-projects/spring-boot/releases)
- [Commits](https://github.com/spring-projects/spring-boot/compare/v2.6.14...v3.0.3)

---
updated-dependencies:
- dependency-name: org.springframework.boot:spring-boot-starter-parent
  dependency-type: direct:production
  update-type: version-update:semver-major
...

Signed-off-by: dependabot[bot] <support@github.com>

* Bump caffeine from 3.1.1 to 3.1.4

Bumps [caffeine](https://github.com/ben-manes/caffeine) from 3.1.1 to 3.1.4.
- [Release notes](https://github.com/ben-manes/caffeine/releases)
- [Commits](https://github.com/ben-manes/caffeine/compare/v3.1.1...v3.1.4)

---
updated-dependencies:
- dependency-name: com.github.ben-manes.caffeine:caffeine
  dependency-type: direct:development
  update-type: version-update:semver-patch
...

Signed-off-by: dependabot[bot] <support@github.com>

* Upgrade in progress

Now to get a Solr instance up and running aside from the test runner

// identify overlapping schema
// remediate overlapping schema

// need mechanism to correct ...

Cleaning up more cruft left behind the hack and slash upgrade

Cleanup while running index...

Correct bad refactor. Try not to break Solr running tests.

jakarta.xml.bind.JAXBException: namespacePrefixMapper is null
        at org.docx4j.jaxb.NamespacePrefixMapperUtils.setProperty(NamespacePrefixMapperUtils.java:150) ~[docx4j-core-11.4.8.jar:na]
        at org.docx4j.openpackaging.contenttype.ContentTypeManager.marshal(ContentTypeManager.java:951) ~[docx4j-core-11.4.8.jar:na]
        at org.docx4j.openpackaging.io3.stores.ZipPartStore.saveContentTypes(ZipPartStore.java:313) ~[docx4j-core-11.4.8.jar:na]
        at org.docx4j.openpackaging.io3.Save.save(Save.java:177) ~[docx4j-core-11.4.8.jar:na]
        at org.docx4j.openpackaging.packages.OpcPackage.save(OpcPackage.java:799) ~[docx4j-core-11.4.8.jar:na]
        at org.docx4j.openpackaging.packages.OpcPackage.save(OpcPackage.java:729) ~[docx4j-core-11.4.8.jar:na]
        at org.docx4j.openpackaging.packages.OpcPackage.save(OpcPackage.java:717) ~[docx4j-core-11.4.8.jar:na]
        at edu.tamu.scholars.middleware.export.service.DocxExporter.lambda$streamIndividual$1(DocxExporter.java:150) ~[classes/:na]
        at org.springframework.web.servlet.mvc.method.annotation.StreamingResponseBodyReturnValueHandler$StreamingResponseBodyTask.call(StreamingResponseBodyReturnValueHandler.java:110) ~[spring-webmvc-6.0.6.jar:6.0.6]
        at org.springframework.web.servlet.mvc.method.annotation.StreamingResponseBodyReturnValueHandler$StreamingResponseBodyTask.call(StreamingResponseBodyReturnValueHandler.java:97) ~[spring-webmvc-6.0.6.jar:6.0.6]
        at org.springframework.web.context.request.async.WebAsyncManager.lambda$startCallableProcessing$4(WebAsyncManager.java:336) ~[spring-web-6.0.6.jar:6.0.6]
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) ~[na:na]
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[na:na]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[na:na]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[na:na]
        at java.base/java.lang.Thread.run(Thread.java:833) ~[na:na]

org.docx4j.openpackaging.exceptions.Docx4JException: Error marshalling Content_Types
        at org.docx4j.openpackaging.io3.stores.ZipPartStore.saveContentTypes(ZipPartStore.java:317)
        at org.docx4j.openpackaging.io3.Save.save(Save.java:177)
        at org.docx4j.openpackaging.packages.OpcPackage.save(OpcPackage.java:799)
        at org.docx4j.openpackaging.packages.OpcPackage.save(OpcPackage.java:729)
        at org.docx4j.openpackaging.packages.OpcPackage.save(OpcPackage.java:717)
        at edu.tamu.scholars.middleware.export.service.DocxExporter.lambda$streamIndividual$1(DocxExporter.java:150)
        at org.springframework.web.servlet.mvc.method.annotation.StreamingResponseBodyReturnValueHandler$StreamingResponseBodyTask.call(StreamingResponseBodyReturnValueHandler.java:110)
        at org.springframework.web.servlet.mvc.method.annotation.StreamingResponseBodyReturnValueHandler$StreamingResponseBodyTask.call(StreamingResponseBodyReturnValueHandler.java:97)
        at org.springframework.web.context.request.async.WebAsyncManager.lambda$startCallableProcessing$4(WebAsyncManager.java:336)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base/java.lang.Thread.run(Thread.java:833)

---------

Signed-off-by: dependabot[bot] <support@github.com>
Co-authored-by: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>